# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 154458241e6f96b530a7ed56297b45bb7ec954c68f21e475c1cb684ba4ce7b629b2b7072c85372e81367f08672bcc4960f0c0798d04aa3731e02f29aa9ec6da0

test:
  secret_key_base: f93d9c2256d55f34f71584f845e0715a9b41da8b36678d4c68115b9c5cfe81b5f04dd1b68c4395611c2c036b6733b41278dc7be470bce9e0ec3ad6b055ae2889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
